# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSSample
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'
  pod 'PKHUD', '~> 5.0'
  pod 'SQLite.swift', '~> 0.11.5'
end
